### ISSUE TITLE
No buildable Go source files in …/lib/render/textmate

### ISSUE THREAD

**Issue by michael-k** [limetext/lime-backend#63]
When running `go get`, I get an build error.  I can build limetext (i.e., all frontends) anyway.

```
$ go get github.com/limetext/lime-backend/lib/...
go build github.com/limetext/lime-backend/lib/render/textmate: no buildable Go source files in $GOPATH/src/github.com/limetext/lime-backend/lib/render/textmate
```

**Comment by erbridge** [comment]
@quarnster: why is the syntax file excluded from builds?

**Comment by quarnster** [comment]
Because it doesn't compile :)

The interfaces changed and since this code wasn't used anyway I added a build tag to look at it at a later date.

**Comment by quarnster** [comment]
Add: it could be removed as a "fix", it's not used right now anyway
