### ISSUE TITLE
clang: error: -E or -x required when input is from standard input

### ISSUE THREAD

**Issue by tvrc4m** [limetext/lime-backend#76]
install sublime text plugin.
the following sublime text debug data:

using gpu buffer for window
reloading Packages/completion/completion.sublime-settings
Prepare: 0.205040 ms
connect to '/var/root/Library/Application Support/Sublime Text 3/Packages/User/completion.rpc'
--> '{"method": "Clang.CompleteAt", "params": [{"Location": {"File": {"Name": "/imaginato/qraved/Qraved/Qraved/AppDelegate.h", "Contents": "//\\n//  AppDelegate.h\\n//  Qraved\\n//\\n//  Created by Shine Wang on 5/30/13.\\n//  Copyright (c) 2013 ShineWang. All rights reserved.\\n//\\n\\n#import <UIKit/UIKit.h>\\n#import <CoreLocation/CoreLocation.h>\\n#import <FacebookSDK/FacebookSDK.h>\\n#import \\"GAI.h\\"\\n#import \\"LoginViewController.h\\"\\n#import \\"MainMenuViewController.h\\"\\n#import \\"HomeViewController.h\\"\\n//#import \\"QrarvedIncrementalStore.h\\"\\n#import \\"ProfileViewController.h\\"\\n#import \\"MLNavigationController.h\\"\\n#import \\"PointRewardsViewController.h\\"\\n#import \\"SettingViewController.h\\"\\n\\n#import \\"Helper.h\\"\\n\\n#import \\"RESideMenu.h\\"\\n#import <LayerKit/LayerKit.h>\\n\\n@interface AppDelegate : UIResponder <UIApplicationDelegate,CLLocationManagerDelegate,UIActionSheetDelegate,UIImagePickerControllerDelegate,UINavigationControllerDelegate,RESideMenuDelegate>\\n\\n@property(nonatomic, strong) id<GAITracker> tracker;\\n@property(nonatomic, retain) CLLocationManager *locationManager;\\n@property (strong, nonatomic) UIWindow *window;\\n\\n@property(nonatomic,retain)RESideMenu *sideMenuViewController;\\n@property(nonatomic,retain)CLLocation *currentLocation;\\n\\n@property(nonatomic,assign)BOOL userLogined;\\n@property(nonatomic,assign)BOOL qraveRefresh;\\n//@property(nonatomic,assign)BOOL isShare;\\n//@property(nonatomic,assign)BOOL isUpload;\\n@property(nonatomic,retain)NSMutableDictionary *uploadPictureDic;\\n\\n@property (readonly, strong, nonatomic) NSManagedObjectContext *managedObjectContext;\\n@property (readonly, strong, nonatomic) NSManagedObjectModel *managedObjectModel;\\n@property (readonly, strong, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;\\n//@property (readonly, strong, nonatomic) AFIncrementalStore *incrementalStore ;\\n\\n@property (assign) int touchedIndex;\\n\\n@property(nonatomic,assign) NSInteger selectedPrice;\\n\\n@property (nonatomic, strong) HomeViewController *homeViewController;\\n\\n@property (nonatomic, strong) ProfileViewController *myProfileViewController;\\n\\n@property (nonatomic, strong) PointRewardsViewController *pointRewardViewController;\\n\\n@property (nonatomic, strong) SettingViewController *settingViewController;\\n\\n@property (nonatomic, strong) MLNavigationController *homeNavigationController;\\n@property (nonatomic, strong) MLNavigationController *qraveNavigationController;\\n@property (nonatomic, strong) MLNavigationController *searchNavigationController;\\n@property (nonatomic, strong) UINavigationController *filterNavigationController;\\n@property (nonatomic, strong) MLNavigationController *ProfileNavigationController;\\n@property (nonatomic, strong) UINavigationController *loginNavagationController;\\n@property (nonatomic, strong) MLNavigationController *pointRewardsNavigationController;\\n@property (nonatomic, strong) MLNavigationController *settingNavigationController;\\n@property (nonatomic, strong) MainMenuViewController *mainMenuViewController;\\n@property(nonatomic,retain)UINavigationController *selectedNavigationController;\\n//\\u5224\\u65ad\\u662f\\u5426\\u767b\\u5f55\\n\\n@property(nonatomic,retain) NSMutableArray * eatjktData;\\n@property(nonatomic,retain)NSMutableArray *splashsArray;\\n//@property(nonatomic,retain)NSString *kTrackingId;\\n\\n- (NSURL *)applicationDocumentsDirectory;\\n\\n-(void)goToPage:(NSInteger)tabIndex;\\n-(void)goToPage:(NSInteger)tabIndex  withSearchTag:(NSDictionary*)searchTag withEventLogo:(NSString*)eventLogo;\\n-(void)goToLoginController:(NSNumber *)fromWhere;\\n-(void)goToLoginController;\\n-(void)requestToShowNotificationCount;\\n-(void)clearNotificationCount;\\nN\\n-(BOOL)isShowEvent;\\n\\n// Layer\\n-(void)loadLayerButton;\\n-(void)HideLayerWindow;\\n\\n\\n+(AppDelegate *)ShareApp;\\n@end\\n"}, "Column": 2, "Line": 83}, "SessionOverrides": {"compiler_flags": [], "net_paths": [], "net_assemblies": []}}], "id": 0}'
<-- b'{"id":0,"result":null,"error":"clang: error: -E or -x required when input is from standard input\\n"}\n'
close '/var/root/Library/Application Support/Sublime Text 3/Packages/User/completion.rpc'
clang: error: -E or -x required when input is from standard input

**Comment by erbridge** [comment]
Sorry, but this doesn't look like it has anything to do with Lime Text. Try contacting the package owner.
