### ISSUE TITLE
Is the project still alive

### ISSUE THREAD

**Issue by jahan01** [limetext/lime-backend#81]
Is the project still alive? Is it worth to make an effort to contribute? It sounded like an best alternative to sublime text which is a dead project. But this project itself seems to be dying

**Comment by Psyringe** [comment]
Agreed. I really like to use an open-source alternative. Atom feels laggy and heavy, and is kinda bloated.

**Comment by ricochet1k** [comment]
I agree also. I've been working a bit on the QML frontend and making a lot of progress. I'm going to start pushing commits to a fork soon.

**Comment by erbridge** [comment]
The project is only as alive as its contributors. I still believe in the project, but my time is too limited right now to do any meaningful work on it. If you have time, we'd love for your help.

**Comment by zoli** [comment]
After several months that I hadn't enough time for contributing. I am going to start working on this project again, it won't be much but I hope others will join and we could move limetext forward.

**Comment by kolkov** [comment]
Good news! We need this open source project on go!

**Comment by Borderliner** [comment]
Keep it alive please. For those who are tired of Atom's sluggish interface and Sublime's annoying register pop-ups, this would be the best alternative. I'd help if I could, but I'm not a C++/QML guy.

**Comment by Theodus** [comment]
You don't have to have experience in C++ or QML. There are frontends for the terminal and for HTML/Javascript. The backend is also separated entirely from the frontends and almost all written in Go or Javascript.

**Comment by ricochet1k** [comment]
Backend in Javascript? You don't mean the Python plugins do you?

**Comment by clawoflight** [comment]
@Borderliner How about you buy Sublime if you like it!?

**Comment by Borderliner** [comment]
@clawoflight Not that it's any of somebody's business, but it's not possible to do an international money transaction from Iran. How about you buy it for me?

**Comment by stoatally** [comment]
Is there a place where people working on this regularly hang out? Perhaps an IRC channel? I'd like to get involved but I feel that it would be best to catch up with someone who's already worked on it before I begin.

I've just spent this weekend completely gutting Sublime Text in order to allow me to add a better build system, but because it's closed source I cannot fix some things and I cannot share the results with my colleagues.

**Comment by akarki15** [comment]
@stoatally http://webchat.freenode.net/?channels=limetext
