### ISSUE TITLE
Panic in inputthread: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by epitron** [limetext/lime-backend#83]
Hi!

I'm unable to run the backend on Arch Linux. I'm using go 1.6.

Here's the test output: https://gist.github.com/epitron/af815a80c2c631ab65a1

Is this a common problem?

**Comment by zoli** [comment]
Yes there is a problem with [TestHandleInput](https://github.com/limetext/lime-backend/blob/master/lib/editor_test.go#L192).
